### PR TITLE
Features/notation-declaration

### PR DESCRIPTION
**Pull request by eosram**
On the one hand I would like to include the mathematical notation in our repository for documentation purposes, although maybe in a separate file in the future. On the other hand I've spotted minor inconsistencies in the use of the common terminology. To prevent this I introduced an additional layer between the common terminology and the LaTeX formulas. I would propose to use substitutions for variable and parameter names in the common terminology. It is slightly easier to read and if only placeholder names are allowed in the formulas then there cannot be inconsistencies.This would also allow for changes in the naming convention later on.

### CODE REVIEW

**Comment by IdaGJ** [comment]
I think this is a great idea (We actually also thought about making a layer from Balmorel to the common terminology but felt it was a waste of time - this seems to be a bit more doable).

I tried switching to the branch but it seems like I am missing some thing from the environment file - it says: "Extension error: Could not import extension fluiddoc.mathmacro (exception: No module named 'fluiddoc')". How would I handle that?

**Comment by eosram** [comment]
Ah, sry, I haven't updated the environment file. I will look into that. The fluiddyn package is needed.

**Comment by eosram** [comment]
So this could work in the meantime. 
```
 conda install -c conda-forge fluiddyn 
```

**Comment by IdaGJ** [comment]
So now, I did make it work! Instead of it being inside the modelling of technologies, should it be on the very first page of the mathdoc? Then we could also use it inside the subpages for each framework.

I did make quite some changes to the master branch yesterday (only the modelling of technologies page), so when you merge it, it would be nice to double check that it is still the same order as in the current master :-)

And of course - maybe wait with merging until you have edited the environment file too.

**Comment by eosram** [comment]
I guess it should work if the macros are defined in one place and other `rst`-files use the `include` directive . I will try that. Yeah, you're right, the declaration of the notation should be moved to the index file then.

**Comment by eosram** [comment]
The pull request introduces a change in the workflow of adding formulas. Because new formulas will be added soon, I decided to merge the pull request, although the notation and the macros don't reflect all of the already existing terminology yet. New terms should be added when needed then.

**Pull request merged**
